services:
  vertex:
    build:
      context: .
      dockerfile: Dockerfile
    image: vioeloria/vertex:latest
    container_name: vertex-mod
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      PUID: 0
      PGID: 0
      PORT: 3000
      REDISPORT: 6379
    ports:
      - "3077:3000"
    volumes:
      - ./vertex:/vertex
    stop_grace_period: 30s
